import { useEffect, useState } from 'react';
import Head from 'next/head';
import styles from '@/styles/Dashboard.module.css';
import Image from 'next/image';

export default function Dashboard() {
  const [meals, setMeals] = useState([]);
  const [currentMeal, setCurrentMeal] = useState({});

  const fetchMealInfoData = () => {
    const jwtToken = localStorage.getItem('token');
    fetch('https://ciaochow.plusnarrative.biz/api/chows?populate=*', {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${jwtToken}`,
      },
    })
      .then((response) => {
        return response.json();
      })
      .then((data) => {
        if (data?.error) {
          alert(data.error.message);
        }
        if (data?.meta?.pagination?.total) {
          setMeals(data.data);
          setCurrentMeal(data.data[0]);
        }
      })
      .catch((error) => {
        alert('Something went wrong. Please try again later.');
      });
  };

  useEffect(() => {
    fetchMealInfoData();
  }, []);

  const setRandomMeal = () => {
    let randomMeal = meals[Math.floor(Math.random() * meals.length)];

    // Check if the randomMeal is the same as the currentMeal
    while (randomMeal === currentMeal) {
      randomMeal = meals[Math.floor(Math.random() * meals.length)];
    }

    setCurrentMeal(randomMeal);
  };

  if (!currentMeal || meals.length == 0) return <div>Loading...</div>;

  const imageUrl =
    'https://ciaochow.plusnarrative.biz' +
    currentMeal?.attributes?.Image?.data[0]?.attributes?.url;

  return (
    <>
      <Head>
        <title>CiaoChow - Meal</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.svg' />
      </Head>
      <main className={`${styles.dashboardBackground} appWrap`}>
        <Image
          src={imageUrl}
          width={100}
          height={100}
          alt='CiaoChow Meal'
          className={styles.mealImage}
        />
        <div className={styles.mealInfo}>
          <div className={styles.mealHeader}>
            <h1 className={styles.mealTitle}>
              {currentMeal?.attributes?.Title}
            </h1>
            <Image
              src='/images/dashboard/like.svg'
              width={100}
              height={100}
              alt='CiaoChow Like Meal'
              className={styles.likeMealIcon}
            />
          </div>
          <div className={styles.mealButtonsContainer}>
            <button
              className={`${styles.mealDescriptionButton} ${styles.mealActiveButton}`}
            >
              Description
            </button>
            <button className={styles.mealFactsButton}>Nutrition facts</button>
          </div>
          <div className={styles.mealDescription}>
            {currentMeal?.attributes?.Description}
          </div>
          <div className={styles.nextButtonContainer}>
            <button className={styles.nextButton} onClick={setRandomMeal}>
              Nah! Find something else.
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
