import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>CiaoChow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className={`${styles.homeBackground} appWrap`}>
        <Image src="/images/welcome/ellipse.svg" width={100} height={100} alt="CiaoChow" className='backgrounImage' />
        <Image src="/images/welcome/logo.svg" width={100} height={100} alt="CiaoChow logo" className={styles.logo} />
        <Image src="/images/welcome/charactors.svg" width={100} height={100} alt="CiaoChow charactors" className={styles.charactors} />
        <p className={styles.content}> 
          Hungry? <b>CiaoChow</b> helps you find something to eat. 
        </p>
        <button className={styles.button}>
          Get Started
        </button>
        <Image src="/images/welcome/dots.svg" width={100} height={100} alt="CiaoChow navigation dots" className={styles.navigationDots} />
      </main>
    </>
  )
}
